<?php

namespace Omnipay\eProcessingNetwork\Message;

use Omnipay\Common\Message\AbstractResponse as OmnipayAbstractResponse;

class Response extends OmnipayAbstractResponse
{
    public function getMessage(): string
    {
        return $this->getValue('RespText');
    }

    /**
     * Gateway Reference
     *
     * @return null|string A reference provided by the gateway to represent this transaction
     */
    public function getTransactionReference(): ?string
    {
        return $this->getValue('Tran_token');
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @return string|null
     */
    public function getTransactionId(): ?string
    {
        return $this->getValue('XactID');
    }

    /**
     * Get the invoice ID as generated by the merchant website.
     *
     * @return string
     */
    public function getInvoiceId(): string
    {
        return $this->getValue('Invoice');
    }

    /**
     * Get the recurring ID as generated by the merchant website.
     *
     * @return string
     */
    public function getSubscriptionId(): string
    {
        return $this->getValue('RecurID');
    }

    public function isSuccessful(): bool
    {
        return strcasecmp($this->getValue('Success'), 'y') === 0;
    }

    /**
     * @param string $key
     * @return string|null
     */
    protected function getValue(string $key): ?string
    {
        return $this->getData()[$key] ?? null;
    }
}
